### PR TITLE
Fixed bug that caused WebP parameter value 0 to be ignored

### PR DESCRIPTION
**Pull request by AaaK00**
Found out that zero cannot be given as parameter to WebP options. For example, code:
```
let options = [.encodeWebPMethod: 0, .encodeWebPAlphaCompression: 100]
let data = SDImageWebPCoder.shared.encodedData(with: image, format: .webP, options: options)
```
Does not work correctly. Default value for WebP method (4) is used instead of 0.

Issue is caused by the fact that comparison 
```
if ([options[SDImageCoderEncodeWebPMethod] intValue])
```
results to false when intValue is 0.

Fixed by changing the logic of how it is concluded whether value for certain option has been provided. Also updated unit tests so they catch similar issues in future.

### CODE REVIEW

**Comment by dreampiggy** [comment]
That helper method `getIntValueFor:defaultValue:options:` looks really strange. Not a good design. (Only works in fucntion)

Why not use something like this:

```objective-c
static int GetIntValueForKey(NSDictionary *dictionary, NSString *key, int defaultValue) {
   // ... same implementation
}
```

Or even a extension to NSDictionary, but I think since SDWebImageWebPCoder is simple codec, add extension to NSDictionary class will increase binary size and have to use something like prefix style API `sd_intValueForKey:`, which I dislike...

So a single inline or static C function is better.

**Comment by AaaK00** [comment]
> That helper method `getIntValueFor:defaultValue:options:` looks really strange. Not a good design for SDK development. (Only works in this context, why not more generic)
> 
> Use something like this:
> 
> ```objc
> static int GetIntValueForKey(NSDictionary * _Nonnull dictionary, NSString * _Nonnull key, int defaultValue) {
>    // ... same implementation
> }
> ```
> 
> Or even a extension to NSDictionary, but I think since SDWebImageWebPCoder is simple codec wrapper. Adding extension to NSDictionary class will increase binary size and have to use something like prefix style API `sd_intValueForKey:`, which I dislike...
> 
> So a single inline or static C function is better.

Yeap, good point. Probably better to use plain static C function. Better now?

**Comment by dreampiggy** [comment]
LGTM now. I'll merge and release new version.

**Comment by dreampiggy** [comment]
Released [v0.8.1](https://github.com/SDWebImage/SDWebImageWebPCoder/releases/tag/0.8.1)

**Pull request merged**
