### PR TITLE
change the deployment target to iOS 9 to use with Xcode 12

### PR DESCRIPTION
**Pull request by shimastripe**
## WHY

- Xcode 12 doesn’t support 8 anymore and will fail to compile

## WHAT

- Change the deployment target to iOS9
- I searched the whole files and change versions around library settings.
  - Readme
  - Cocoa pod
  - SPM

### CODE REVIEW

**Comment by luan-sala** [comment]
is there some news on this PR?
I need to just wait for a new release?

**Comment by dreampiggy** [comment]
This is a major break to exist user.

Because Apple still supports Xcode 10 to submit Apps. We can not do this until 6.x

**Comment by eseay** [comment]
@dreampiggy What would you suggest as the workaround for this issue then? While technically it sunsets support for old versions of Xcode, failure to implement this prevents teams that rely on this framework from building their apps with Xcode 12. In many cases, using Xcode 12 is not an optional thing, as teams have commitments to shipping iOS 14 functionality at launch.

**Comment by dreampiggy** [comment]
> @dreampiggy What would you suggest as the workaround for this issue then? While technically it sunsets support for old versions of Xcode, failure to implement this prevents teams that rely on this framework from building their apps with Xcode 12. In many cases, using Xcode 12 is not an optional thing, as teams have commitments to shipping iOS 14 functionality at launch.

You can just, for example, use CocoaPods's post-installer, or Carthage 's `carthage update --no-build` and change the build settings by your own.

Framework author can suggest the min deployment target version, but as a integrator, you can also modify the min deployment target version.

**Comment by dreampiggy** [comment]
If you don't know how to Change the min deployment target version, See someone's readme like this:

https://github.com/SDWebImage/SDWebImageSwiftUI#backward-deployment-on-ios-121-

**Comment by dreampiggy** [comment]
You can also have a wait for SDWebImage 6.0, which will drop the iOS 9 support. So do this WebP coder.

**Comment by eseay** [comment]
Got it. Those are fair suggestions. Our team uses Swift Package Manager, so for the time being, I think the most appropriate approach may just be for me to fork my own copy of this repository and make the necessary changes. Do you have any approximate timeline on v6.0?

**Comment by dreampiggy** [comment]
> Got it. Those are fair suggestions. Our team uses Swift Package Manager, so for the time being, I think the most appropriate approach may just be for me to fork my own copy of this repository and make the necessary changes. Do you have any approximate timeline on v6.0?

If SDWebImage milestone v6.0 can not get scheduled in September. (Xcode 12 GM may be released in Sep 10th). We will release a new minor version (like SDWebImage 5.10.0) and change the min deployment target version to iOS 9+.

This effects all SDWebImage community components: https://github.com/SDWebImage, nearly 20 of them. So instead of fixing one by one, we will submit 20 PRs at the same time for this task.

**Comment by dreampiggy** [comment]
@shimastripe  I found this `'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0` is just warning, not compile error. Are you sure this cause issues ?

**Comment by dreampiggy** [comment]
image

**Comment by shimastripe** [comment]
@dreampiggy Thank you for your reply. It seems that Xcode12-beta consider sub library (on which the library depends) as 9.0 deployment target. SDWebImageWebPCoder depends on libwebp and Xcode compiler considers libwebp's deployment target as 9.0. If the library depends no sub libraries, as you said, Xcode compiler displays only warning.

スクリーンショット 2020-08-28 15 04 40
スクリーンショット 2020-08-28 15 04 56

Please you check it out imported by another project.

**Comment by dreampiggy** [comment]
So, I just release an libwebp with min deployment target version iOS 8.0, this issue can be solved ?


https://github.com/SDWebImage/libwebp-Xcode

**Comment by dreampiggy** [comment]
The libwebp seems have no explicit min deployment version set, not a good practice. We may provide a fix version.

**Comment by shimastripe** [comment]
@dreampiggy https://github.com/SDWebImage/libwebp-Xcode/compare/1.1.0...shimastripe:1.4.0 I checked it by myself about libwebp-xcode. However, the error was not resolved. Is there something wrong with this procedure?

**Comment by jondwillis** [comment]
@shimastripe I submitted a PR to your repo. https://github.com/shimastripe/SDWebImageWebPCoder/pull/1

**Comment by dreampiggy** [comment]
> @dreampiggy [SDWebImage/libwebp-Xcode@1.1.0...shimastripe:1.4.0](https://github.com/SDWebImage/libwebp-Xcode/compare/1.1.0...shimastripe:1.4.0) I checked it by myself about libwebp-xcode. However, the error was not resolved. Is there something wrong with this procedure?

You should limit the `Package.swift` platform version to iOS 8, not iOS 9.

This not a problem I think. What you two feedbback is :

When I use SwiftPM, Xcode complain sub-dependency use iOS 9+, howwever, SDWebImageWebP use iOS 8+.

We can just fix this, by change the sub-dependency to iOS 8+. Not iOS 9.

**Comment by dreampiggy** [comment]
@shimastripe Try this branch instead: https://github.com/SDWebImage/libwebp-Xcode/pull/5

**Comment by shimastripe** [comment]
@dreampiggy I'm sorry to reply late. I check the `platfrom` branch in libwebp, and it works in Xcode 12 (12A7209)!

**Pull request closed without merging**
